#pragma once

enum BlockType : unsigned char
{
    EMPTY, GRASS, DIRT, STONE, WOOD, LEAF, BEDROCK, LAVA, WATER, ICE, SNOW, SAND,
    BLACK, DARK_GRAY, RED, PINK, DARK_GREEN, GREEN, BROWN, YELLOW, DARK_BLUE, BLUE,
    PURPLE, MAGENTA, TURQOUISE, ORANGE, GRAY
};
